# Data structuring, part 1

### The Pandas way

*Andreas Bjerre-Nielsen*

# Recap

*Which Python containers have learned about so far?*

- list
- dict

*Which containers can we turn into a `numpy array`?*

- list of lists

## Agenda
1. [motivation](#Why-we-structure-data)
2. [the numpy module](#Numpy-module)
3. [overview](#Pandas-overview) of the pandas module: 
4. the pandas series
  - [working with series](#Working-with-pandas-Series) and [numeric procedures](#Numeric-procedures) 
  - [boolean series](#Boolean-Series)
5. more tools:
 - [inspecting and selecting observations](#Inspecting-and-selecting-observations) 
 - [modifying DataFrames](#Modifying-DataFrames)  
 - [dataframe IO](#DataFrame-IO:-loading-and-storing)

# Why we structure data

## Motivation
*Why do we want to learn data structuring?*

- Data never comes in the form of our model. We need to 'wrangle' our data.

*Can our machine learning models not do this for us?* 

- Not yet :). The current version needs **tidy** data. What is tidy? 

One row per observation.

## Loading the software

In [205]:
import numpy as np
import pandas as pd

# Numpy module

## Numpy overview
*What is the [`numpy`](http://www.numpy.org/) module?*

`numpy` is a Python framework similar to matlab 
- fast and versatile for manipulating arrays
- linear algebra tools available
- many machine learning and statistics libraries are built with `numpy`

## Numpy arrays
*What is a numpy array?*

An n-dimensional array:  
- 1-d: vector;
- 2-d: matrix;
- 3-d: tensor.  

We see use cases later.

# Pandas overview

## Pandas motivation
*Why use Pandas?*

1. simplicity - Pandas is built with Python's simplicity 
1. flexible and powerful tools for manipulating data
1. speed - build on years of research about numeric computation
1. development - breathtaking speed of new tools coming

## Pandas data types
*How do we work with data in Pandas?*

- We use two fundamental data stuctures: ``Series`` and ``DataFrame``.

## Pandas data frames (1)

*What is a `DataFrame`?*

- A matrix with labelled columns and rows (which are called indices). Example:

In [206]:
df = pd.DataFrame([[1,2], [3,4]],
                  index=['i', 'ii'],
                  columns=['A', 'B'])

print(df)

    A  B
i   1  2
ii  3  4


- An object with powerful data tools.

## Pandas data frames (2)

*How are pandas dataframes built?*

Pandas dataframes can be though of as numpy arrays with some additional stuff.

Most functions from `numpy` can be applied directly to Pandas. We can convert a DataFrame to a `numpy` matrix with `values` attribute.

In [207]:
df.values

array([[1, 2],
       [3, 4]], dtype=int64)

*To note*: In Python we can describe it as a list of lists of a dict of dicts.

## Pandas series
*What is a `Series`?*

- A vector/list with labels for each entry. Example:

In [208]:
L = [1, 1.2, 'abc', True]

my_series = pd.Series(L)
my_series.to_dict()

{0: 1, 1: 1.2, 2: 'abc', 3: True}

*What data structure does this remind us of?*



- A mix of Python list and dictionary (more info follows)

## Series vs DataFrames
*How are Series related to DataFrames?*

Every column is a series. Example: access as object method:

In [209]:
print(df.A)

i     1
ii    3
Name: A, dtype: int64


Another option is access as key:

In [210]:
print(df['B'])

i     2
ii    4
Name: B, dtype: int64



*To note:* The latter option more robust as variables named same as methods, e.g. `count`, cannot be accesed.

## Indices and column names
*Why don't we just use matrices?*

- inspection of data is quicker 
- keep track of rows after deletion
- indices may contain fundamentally different data structures
    - e.g. time series, hierarchical groups
- facilitates complex operation:
    - merging datasets
    - split-apply-combine

# Working with pandas Series

## Generate Series (1)
Let's revisit our series

In [211]:
my_series

0       1
1     1.2
2     abc
3    True
dtype: object

Components in series 
- `index`: label for each observation
- `values`: observation data
- `dtype`: the format of the series - `object` means any data type is allowed
  - note: the object dtype is SLOW!

## Generate Series (2)
*How do we set custom index?* 

Example:

In [212]:
num_data = range(0,3)
indices = ['B', 'C', 'A']
my_series2 = pd.Series(num_data, index=indices)
my_series2

B    0
C    1
A    2
dtype: int64

## Generation Series (3)
*Can a dictionary be converted to a series?*

Yes, we just put into the Series class constructor. Example:

In [213]:
d = {'yesterday': 0, 'today': 1, 'tomorrow':3}
my_series3 = pd.Series(d)
my_series3

today        1
tomorrow     3
yesterday    0
dtype: int64

Note: Same is true for DataFrames which requires that each value in the dictionary is also a dictionary.

## Generation Series (4)
*Can we convert series to dictionaries?*

- Yes, in most cases. 

- ***WARNING!#@***: Series indices are NOT unique

In [214]:
s = pd.Series(range(3),index=['A', 'A','A'])
s.index.duplicated().sum()

2

## The power of pandas
*How is the series different from a dict?*

- We will see that pandas Series have powerful methods and operations.
- It is both key and index based.

## Converting data types 

The data type of a series can be converted with the **astype** method:

In [215]:
my_series3.astype(np.float64) # np.str

today        1.0
tomorrow     3.0
yesterday    0.0
dtype: float64

# Numeric procedures

## Numeric operations (1)
*How can we basic arithmetic operations with arrays, series and dataframes?*

Like Python data! An example:

In [216]:
my_arr1 = np.array([2,3,2])
my_arr2 = my_arr1 ** 2
my_arr2

array([4, 9, 4], dtype=int32)

## Numeric operations (2)
*Are other numeric python operators the same??*

Numeric operators work `/`, `//`, `-`, `*`, `**`  as expected.

*Why is this useful?*

- vectorized operations are VERY fast;
- requires very little code.

## Numeric operations (3)
*Can we do the same with two vectors?*

- Yes, we can also do elementwise addition, multiplication, subtractions etc. of series. Example: 

In [217]:
my_arr1 + my_arr2

array([ 6, 12,  6])

## Numeric methods (1)

Pandas series has powerful numeric methods built-in, example:

In [218]:
arr = np.random.normal(size=10**7)
s2 = pd.Series(arr)
s2.median()

1.149038317919818e-06

Other useful methods include: `mean`, `quantile`, `min`, `max`, `std`, `describe`, `quantile` and many more.

In [219]:
my_series2.describe()

count    3.0
mean     1.0
std      1.0
min      0.0
25%      0.5
50%      1.0
75%      1.5
max      2.0
dtype: float64

## Numeric methods (2)
An important method is `value_counts`. This counts number for each observation. 

Example:

In [220]:
my_series4 = pd.Series(my_arr2)
my_series4.unique()

array([4, 9], dtype=int64)

In [221]:
my_series4.value_counts()

4    2
9    1
dtype: int64

What is observation in the value_counts output - index or data?

## Numeric methods (3)

*Are there other powerful numeric methods?*

Yes: examples include 
- `unique`, `nunique`: the unique elements and the count of unique elements
- `cut`, `qcut`: partition series into bins 
- `diff`: difference every two consecutive observations
- `cumsum`: cumulative sum
- `nlargest`, `nsmallest`: the n largest elements 
- `idxmin`, `idxmax`: index which is minimal/maximal 
- `corr`: correlation matrix

Check [series documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.html) for more information.

# Boolean Series

## Logical expression for Series
*Can we test an expression for all elements?*

Yes: **==**, **!=** work for a single object or Series with same indices. Example:

In [222]:
my_series3 == 0 

today        False
tomorrow     False
yesterday     True
dtype: bool

What datatype is returned? 


## Logical expression in Series (2)
*Can we check if elements in a series equal some element in a container?*

Yes, the `isin` method. Example:

In [223]:
my_rng = range(2)
print(list(my_rng))
my_series3.isin(my_rng)

[0, 1]


today         True
tomorrow     False
yesterday     True
dtype: bool

## Power of boolean series (1)
*Can we combine boolean Series?*

Yes, we can use:
- the `&` operator (*and*)
- the `|` operator (*or*)

In [224]:
print((my_series3 > 0) & (my_series3 == 1))

today         True
tomorrow     False
yesterday    False
dtype: bool


In [225]:
(df.A > 2) & (df.B<=3) # selection by multiple columns

i     False
ii    False
dtype: bool

What datatype is returned? 


## Power of boolean series (2)
*Why do we care for boolean series (and arrays)?*

Because we can use the to select rows based on their content.

In [226]:
my_series3[my_series3<3]

today        1
yesterday    0
dtype: int64

NOTE: Boolean selection is extremely useful for dataframes!!

# Inspecting and selecting observations

## Viewing series and dataframes
*How can we view the contents in our dataset?*
- We can use `print` our dataset
- We can visualize patterns by plotting (from tomorrow)

## The head and tail

We select the *first* rows in a DataFrame or Series with the `head` method.

In [227]:
n = 3 # number of observations
arr = np.random.normal(size=[100])
my_series7 = pd.Series(arr)
my_series7.head(3)

0    0.094462
1   -0.533870
2    0.004928
dtype: float64

The `tail` method selects the last observations in a DataFrame. 

## Row selection (1)
*How can we select certain rows in a Series when for given index **keys**?* 

WIth the `loc` attribute. Example:

In [228]:
# my_loc = 'tomorrow'
my_loc = ['today', 'tomorrow']
my_series3.loc[my_loc]

today       1
tomorrow    3
dtype: int64

## Row selection (2)
*How can we select certain rows in a Series when for given index **integers**?* 

The `iloc` method selects rows for provided index integers. 

In [229]:
# print(my_series3.iloc[1])
# print(my_series3)
# arr = np.random.normal(size=10**6)
pd.Series(arr).iloc[500010:500013]

Series([], dtype: float64)

## Row selection (3)
*Do our tools for vieving specific rows, i.e. `loc`, `iloc` work for DataFrames?* 

- Yes, we can use both `loc` and `iloc`. As default they work the same.

In [230]:
my_idx = ['i', 'ii', 'iii']
my_cols = ['a','b']
my_data = [[1, 2], [3, 4], [5, 6]]
my_df = pd.DataFrame(my_data, columns=my_cols, index=my_idx)
# print(my_df)
print(my_df.loc['i'])

a    1
b    2
Name: i, dtype: int64


## Row selection (4)
*How are `loc`, `iloc` different for DataFrames?* 

- For DataFrames we can also specify columns.

In [231]:
idx_keep = ['i','ii']
cols_keep = ['a']
print(my_df.loc[idx_keep, cols_keep])

    a
i   1
ii  3


## Columns selection
*How can we select columns in a DataFrame?* 

- Option 1: using the `[]` and providing a list of columns.
- Option 2: using `loc` and setting row selection as `:`.

In [232]:
print(my_df.loc[:,['b']])

     b
i    2
ii   4
iii  6


## Selection quiz
*What does `:` do in `iloc` or `loc`?* 

Select all rows (columns).

# Modifying DataFrames

## Modyfying DataFrames
*Why do we want to modify DataFrames?*

- Because data rarely comes in the form we want it.


## Chaging the index (1)
*How can we change the index of a DataFrame?*

We change set a DataFrame's index index using its method `set_index`. Example:

In [233]:
print(my_df.set_index('a'))

   b
a   
1  2
3  4
5  6


## Chaging the index (2)
*Is our DataFrame changed? I.e. does it have a new index?*

We can use the keyword `inplace` which will replace the DataFrame:

In [234]:
my_df_a = my_df.set_index('a')

my_df_copy = my_df.copy()
my_df_copy.set_index('a', inplace=True)
print(my_df_copy)

   b
a   
1  2
3  4
5  6


## Chaging the index (3)

Sometimes we wish to remove the index. This is done with the `reset_index` method:

In [235]:
print(my_df.reset_index(drop=True))
# print(my_df)

   a  b
0  1  2
1  3  4
2  5  6


By specifying the keyword `drop`=True  we delete the index. Note `inplace` also works.

*To note:* Indices can have multiple levels, in this case `level` can be specified to delete a specific level.

## Chaging the column names

Column names can be changed with

In [236]:
#option 1
print(my_df)
my_df.columns = ['A', 'B']
print(my_df)
#option 2
my_df.rename(columns={'A':'a'}, inplace=True)
print(my_df)

     a  b
i    1  2
ii   3  4
iii  5  6
     A  B
i    1  2
ii   3  4
iii  5  6
     a  B
i    1  2
ii   3  4
iii  5  6


## Chaging column value
*How can we can update values in a DataFrame?*

In [237]:
print(my_df)

# set uniform value
my_df['B'] = 3
print(my_df)


# set different values
my_df['B'] = [2,17,0] 
print(my_df)

# loc, iloc
my_loc2 = ['i', 'ii']
my_df.loc[my_loc2, 'a'] = 10
print(my_df)

     a  B
i    1  2
ii   3  4
iii  5  6
     a  B
i    1  3
ii   3  3
iii  5  3
     a   B
i    1   2
ii   3  17
iii  5   0
      a   B
i    10   2
ii   10  17
iii   5   0


## Sorting data

A DataFrame can be sorted with `sort_values`; this method takes one or more columns to sort by. 

In [34]:
my_df.sort_values(by='a', ascending=False)

a   b
iii  5   0
ii   3  17
i    1   5

*To note:* Many key word arguments are possible for sort_values, including ascending if for one or more valuable we want descending values. Sorting by index is possible with `sort_index`.

# DataFrame IO: loading and storing

## Reading DataFrames (1)

Download the file from url:

In [35]:
url = 'https://api.statbank.dk/v1/data/FOLK1A/CSV?lang=en&Tid=*'

## Reading DataFrames (2)

Now let's try opening it:

- As local file:

In [36]:
abs_path = 'C:/Users/bvq720/Downloads/FOLK1A.csv' # absolute path 
rel_path = 'FOLK1A.csv' # relative path

df = pd.read_csv(url, sep=';') # open the file as dataframe
print(df.head(2))

      TID  INDHOLD
0  2008Q1  5475791
1  2008Q2  5482266


- absolute path: entire path starting from which disk etc.
- relative paths: from where your program, i.e. Jupyter is

## Reading DataFrames (3)

Now let's try opening it  online file:

In [37]:
df = pd.read_csv(url, sep=';')
print(df.head(3))

      TID  INDHOLD
0  2008Q1  5475791
1  2008Q2  5482266
2  2008Q3  5489022


## Reading other data types

Other pandas readers include:  excel, sql, sas, stata and many more.

*To note:* an incredibly fast and useful module for reading and writing data is [feather](https://github.com/wesm/feather).

## Storing data

Data can be stored in a particular format with to_(FORMAT) where (FORMAT) is the file type such as csv. Let's try with to_csv:



In [38]:
df.to_csv('DST_people_count.csv', index=False)

Should we always set `index=False`. Yes, unless time series!!! Otherwise the index will be exported too!

# The end
[Return to agenda](#Agenda)